### ISSUE TITLE
Could you add a section in README on how to install the chaincode?

### ISSUE THREAD

**Issue by siddjain** [wearetheledger/fabric-network-boilerplate#12]
Hello,

I am getting started with hyperledger fabric and am interested in writing my chaincode in nodejs+typescript. Thanks for the work you have done in creating this boilerplate.

I was wondering if you could add steps on how to install and instantiate the nodejs chaincode?

Also is the nodejs chaincode visible in cleartext on the peers once its installed?

**Comment by Superjo149** [comment]
We are doing installation and instantiation via a bash script, similar to the fabric-samples https://github.com/wearetheledger/fabric-network-boilerplate/blob/master/scripts/startFabric.sh. You can just do it like this. You can also do it via code, but we do not provide this method in the boilerplate. 

I never got that question before. I think so, because you need the source code on there to be able to install it. For nodejs this would be the bundled version, for golang the executable , so not 100% readable. Maybe you can delete it afterwards, not sure.

**Comment by siddjain** [comment]
So is below correct?

- in both cases (go, nodejs) one has to provide sourcecode to the install command (peer chaincode install at https://hyperledger-fabric.readthedocs.io/en/release-1.2/commands/peerchaincode.html)

- in case of Go the sourcecode is compiled and binary installed on peer

- in case of NodeJS the sourcecode will be copied to the peer since NodeJS is interpreted language?

- also it follows that if one is writing chaincode in nodejs there is no need to go through the Go specific prerequisites on https://hyperledger-fabric.readthedocs.io/en/latest/prereqs.html?
